
- name: Install ceilometer-middleware
  hosts: swift_all:swift_remote_all
  gather_facts: "{{ gather_facts | default(True) }}"
  user: root
  tasks:
  - name: Clone ceilometermiddleware fork
    git:
      repo: "https://github.com/sacharya/ceilometermiddleware.git"
      dest: "/opt/rackspace/ceilometermiddleware_fork"
      version: "response_headers"

  - name: Install ceilometermiddleware package
    command: "/openstack/venvs/swift-13.2.0/bin/pip install ."
    args:
      chdir: '/opt/rackspace/ceilometermiddleware_fork'
    become: true
  - name: Restart swift proxy
    service:
      name: swift-proxy-server
      state: restarted
      pattern: swift-proxy-server

  #- name: Patch ceilometer
  #  patch: >
  #    src=patches/ceilometer_swift.py.patch
  #    dest=/openstack/venvs/ceilometer-13.2.0/lib/python2.7/site-packages/ceilometer
  

- name: Install ceilometer
  hosts: ceilometer_all
  gather_facts: "{{ gather_facts | default(True) }}"
  user: root
  tasks:
  - name: Clone ceilometer fork
    git:
      repo: "https://github.com/sacharya/ceilometer.git"
      dest: "/opt/rackspace/ceilometer_fork"
      version: "swift-container-metadata"

  - name: Install ceilometer package
    command: "/openstack/venvs/ceilometer-13.2.0/bin/pip install ."
    args:
      chdir: '/opt/rackspace/ceilometer_fork'
    become: true

  - name: Restart ceilometer poller
    service:
      name: ceilometer-polling
      state: restarted
      pattern: ceilometer-polling

